  
channels:
  - conda-forge
  - pypi
dependencies:
  - appmode=0.7.0=py36_1002
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - plotly=4.6.0=py_0
  - xlrd=1.2.0=py_0
  - pip:
    - cufflinks==0.17.3
